version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: yeoman-generator
    versions:
    - 5.0.0
    - 5.0.1
    - 5.1.0
  - dependency-name: yeoman-test
    versions:
    - 5.0.1
  - dependency-name: eslint-config-xo
    versions:
    - 0.34.0
    - 0.35.0
  - dependency-name: chalk
    versions:
    - 4.1.0
